services:
  api:
    image: whatisl000ve/yofun-backend:latest
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: backend
    working_dir: /var/www
    networks:
      - default-network
    env_file:
      - ./.env.laravel
    depends_on:
      - db

  web-prod:
    image: whatisl000ve/yofun-frontend:latest
    build:
      context: .
      dockerfile: ./docker/node/prod/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - default-network
    depends_on:
      - api

  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    environment:
      POSTGRES_USER: yoroot
      POSTGRES_PASSWORD: OwWh8yumWIDCEiuT
      POSTGRES_DB: yofun
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-network
  server:
    image: nginx:alpine3.20
    container_name: server-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/common/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/common/nginx/logs:/var/log/nginx
    networks:
      - default-network

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data:
