services:
  api:
    image: whatisl000ve/yofun-backend:latest
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: backend
    working_dir: /var/www
    volumes:
      - static-data:/var/www/public
    networks:
      - default-network
    depends_on:
      - db

  web-prod:
    image: whatisl000ve/yofun-frontend:latest
    build:
      context: .
      dockerfile: ./docker/node/prod/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - default-network
    depends_on:
      - api

  server:
    image: whatisl000ve/yofun-webserver:latest
    build:
      context: .
      dockerfile: ./docker/common/nginx/prod/Dockerfile
    container_name: server-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/common/nginx/logs:/var/log/nginx
      - static-data:/var/www/public:ro
    networks:
      - default-network
    depends_on:
      - web-prod
      - api

  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-network

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data:
  static-data:
