services:
  api:
    image: whatisl000ve/yofun-backend:latest
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: backend
    working_dir: /var/www
    volumes:
      - static-data:/var/www/public
    networks:
      - default-network
    depends_on:
      - db

  web-prod:
    image: whatisl000ve/yofun-frontend:latest
    build:
      context: .
      dockerfile: ./docker/node/prod/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - default-network
    depends_on:
      - api

  server:
    image: whatisl000ve/yofun-webserver:latest
    build:
      context: .
      dockerfile: ./docker/common/nginx/prod/Dockerfile
    container_name: server-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/common/nginx/logs:/var/log/nginx
      - static-data:/var/www/public:ro
    networks:
      - default-network
    depends_on:
      - web-prod
      - api

  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/web.yml:/etc/prometheus/web.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=512MB'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    networks:
      - default-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATASOURCE_URL=http://prometheus:9090
      - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - default-network
    depends_on:
      - prometheus

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data:
  static-data: # Для прокидывания статических файлов в nginx
  prometheus-data: # Том для хранения метрик Prometheus
    driver: local
  grafana-data: # Том для хранения данных Grafana
    driver: local
