services:
  api:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: backend
    working_dir: /var/www
    volumes:
      - ./src/backend:/var/www
    networks:
      - default-network

  web-dev:
    build:
      context: .
      dockerfile: ./docker/node/dev/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - default-network
    depends_on:
      - api
    command: npm run dev

  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mari-fun
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-network

  server:
    image: nginx:alpine3.20
    container_name: server-nginx
    ports:
      - "80:80"
    volumes:
      - ./src/backend:/var/www
      - ./docker/common/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/common/nginx/logs:/var/log/nginx
    networks:
      - default-network
    depends_on:
      - web-dev
      - api

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # Том для хранения метрик
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=15d'           # Хранение 15 дней
      - '--storage.tsdb.path=/prometheus'             # Путь для хранения
      - '--storage.tsdb.retention.size=512MB'         # Лимит размера
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    networks:
      - default-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATASOURCE_URL=http://prometheus:9090
      - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - default-network
    depends_on:
      - prometheus

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data:
  prometheus-data: # Том для хранения метрик Prometheus
    driver: local
  grafana-data: # Том для хранения данных Grafana
    driver: local
