services:
  api:
    build:
      dockerfile: ./docker/build/php/Dockerfile
    container_name: backend
    working_dir: /var/www
    volumes:
      - ./src/backend:/var/www
      - ./docker/common/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/common/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/common/php/php.ini:/usr/local/etc/php/php.ini-production
    networks:
      - default-network
    depends_on:
      - redis
    restart: unless-stopped

  web-dev:
    build:
      context: .
      dockerfile: ./docker/build/node/dev/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - default-network
    restart: unless-stopped
    depends_on:
      - api
    command: npm run dev

  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mari-fun
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default-network

  server:
    image: nginx:alpine3.20
    container_name: server-nginx
    ports:
      - "80:80"
    volumes:
      - ./src/backend:/var/www
      - ./docker/common/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/common/nginx/logs:/var/log/nginx
    networks:
      - default-network
    restart: unless-stopped
    depends_on:
      - web-dev
      - api

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/common/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/common/prometheus/web.yml:/etc/prometheus/web.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=512MB'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    networks:
      - default-network
    restart: unless-stopped
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATASOURCE_URL=http://prometheus:9090
      - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/common/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - default-network
    restart: unless-stopped
    depends_on:
      - prometheus

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-secure_passw0rd}
    volumes:
      - redis-data:/data
    networks:
      - default-network
    restart: unless-stopped

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  redis-data:
    driver: local