name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]  # Триггер на пуш в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub предоставляет мощный сервер для сборки

    steps:
      # Шаг 1: Забираем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 3: Собираем и пушим образы через docker-compose
      - name: Build and push images
        run: |
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml push